;this file for FamiTone2 library generated by text2data tool

nesthing_ost_music_data:
	.db 2
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256
	.dw .song1ch0,.song1ch1,.song1ch2,.song1ch3,.song1ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env1,.env0,.env0
	.db $00
	.db $f0 ;instrument $02
	.dw .env2,.env0,.env0
	.db $00
	.db $f0 ;instrument $03
	.dw .env3,.env6,.env0
	.db $00
	.db $f0 ;instrument $04
	.dw .env3,.env7,.env0
	.db $00
	.db $70 ;instrument $06
	.dw .env4,.env0,.env0
	.db $00
	.db $30 ;instrument $07
	.dw .env5,.env0,.env0
	.db $00

.samples:
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;1
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;2
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;3
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;4
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;5
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;6
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;7
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;8
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;9
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;10
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;11
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;12
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;13
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;14
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;15
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;16
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;17
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;18
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;19
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;20
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;21
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;22
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;23
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;24
	.db $00+LOW(FT_DPCM_PTR),$08,$0f	;25
	.db $03+LOW(FT_DPCM_PTR),$14,$0f	;26
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;27
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;28
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;29
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;30
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;31
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;32
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;33
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;34
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;35
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;36
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;37
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;38
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;39
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;40
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;41
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;42
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;43
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;44
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;45
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;46
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;47
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;48
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;49
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;50
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;51
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;52
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;53
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;54
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;55
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;56
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;57
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;58
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;59
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;60
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;61
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;62
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;63

.env0:
	.db $c0,$00,$00
.env1:
	.db $cf,$00,$00
.env2:
	.db $c6,$c8,$c9,$ca,$ca,$00,$04
.env3:
	.db $c7,$c9,$03,$c7,$c7,$00,$04
.env4:
	.db $ca,$c9,$c7,$c5,$00,$03
.env5:
	.db $c7,$c7,$c7,$00,$02
.env6:
	.db $c0,$c0,$c4,$c4,$c7,$c7,$c0,$c0,$c4,$c4,$c7,$c7,$00,$0b
.env7:
	.db $c0,$c0,$c3,$c3,$c7,$c7,$c0,$c0,$c3,$c3,$c7,$c7,$00,$0b


.song0ch0:
	.db $fb,$04
.song0ch0loop:
.ref0:
	.db $84,$3b,$37,$3a,$91,$40,$89,$44,$85,$40,$95,$4b,$44,$91,$40,$8d
	.db $3a,$8d
.ref1:
	.db $33,$37,$32,$91,$40,$89,$44,$85,$40,$95,$45,$4a,$91,$4e,$8d,$4a
	.db $8d
.ref2:
	.db $3b,$37,$3a,$91,$40,$89,$44,$85,$40,$95,$4b,$44,$91,$40,$8d,$3a
	.db $8d
	.db $ff,$11
	.dw .ref1
.ref4:
	.db $3b,$01,$40,$89,$01,$40,$85,$4e,$89,$45,$40,$89,$37,$40,$95,$44
	.db $8d,$4a,$95
.ref5:
	.db $52,$89,$4b,$4e,$8d,$45,$41,$3a,$89,$40,$91,$53,$45,$4f,$41,$4b
	.db $4f,$44,$85,$52,$85,$4a,$8d
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref6:
	.db $8a,$40,$85,$4b,$4f,$52,$95,$5c,$85,$58,$89,$4f,$58,$85,$4f,$52
	.db $89,$4b,$4e,$89,$52,$95
.ref7:
	.db $5c,$89,$58,$89,$52,$8d,$5c,$85,$58,$85,$4a,$85,$52,$8d,$4b,$44
	.db $89,$40,$85,$4a,$85,$4e,$8d
.ref8:
	.db $40,$85,$4b,$4f,$52,$95,$5c,$85,$58,$89,$4f,$58,$85,$4f,$52,$89
	.db $4b,$4e,$89,$52,$95
	.db $ff,$17
	.dw .ref7
	.db $ff,$15
	.dw .ref8
	.db $ff,$17
	.dw .ref7
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref12:
	.db $82,$1a,$85,$32,$85,$1a,$85,$33,$3b,$28,$85,$40,$85,$28,$85,$40
	.db $85,$24,$85,$3c,$85,$24,$85,$3c,$85,$22,$85,$3a,$85,$22,$85,$3a
	.db $85
.ref13:
	.db $1a,$85,$32,$85,$1a,$85,$33,$3b,$28,$85,$40,$85,$28,$85,$40,$85
	.db $24,$85,$3c,$85,$24,$85,$3c,$85,$22,$85,$3b,$41,$45,$4b,$41,$3a
	.db $81
.ref14:
	.db $1a,$85,$32,$85,$1a,$85,$33,$3b,$28,$85,$40,$85,$28,$85,$40,$85
	.db $24,$85,$3c,$85,$24,$85,$3c,$85,$22,$85,$3a,$85,$22,$85,$3a,$85
	.db $ff,$21
	.dw .ref13
	.db $ff,$20
	.dw .ref14
	.db $ff,$21
	.dw .ref13
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref18:
	.db $f9,$85
.ref19:
	.db $f9,$85
.ref20:
	.db $8c,$14,$00,$83,$14,$00,$14,$00,$13,$01,$10,$85,$14,$00,$83,$14
	.db $00,$14,$00,$13,$01,$10,$85,$14,$00,$83,$14,$00,$14,$00,$13,$01
	.db $10,$85,$14,$00,$83,$14,$00,$83,$12,$00,$14,$00,$10,$85
.ref21:
	.db $14,$00,$83,$14,$00,$14,$00,$13,$01,$10,$85,$14,$00,$83,$14,$00
	.db $14,$00,$13,$01,$10,$85,$14,$00,$83,$14,$00,$14,$00,$13,$01,$10
	.db $85,$14,$00,$1c,$00,$14,$00,$0e,$00,$14,$00,$1c,$00,$14,$00,$0e
	.db $00
.ref22:
	.db $1c,$85,$14,$00,$83,$02,$00,$83,$14,$00,$14,$00,$20,$00,$83,$14
	.db $00,$83,$02,$00,$83,$13,$14,$00,$20,$00,$83,$14,$00,$83,$02,$00
	.db $83,$14,$00,$14,$00,$20,$00,$83,$14,$00,$83,$02,$00,$83,$13,$14
	.db $00
	.db $ff,$31
	.dw .ref22
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref24:
	.db $f9,$85
.ref25:
	.db $f9,$85
.ref26:
	.db $32,$85,$32,$85,$34,$85,$32,$85,$32,$85,$32,$85,$34,$85,$32,$85
	.db $32,$85,$32,$85,$34,$85,$32,$85,$32,$85,$32,$85,$34,$85,$33,$32
	.db $81
	.db $ff,$21
	.dw .ref26
.ref28:
	.db $33,$32,$85,$33,$34,$85,$33,$33,$32,$85,$32,$85,$34,$85,$32,$85
	.db $33,$33,$32,$85,$34,$85,$33,$32,$85,$33,$32,$85,$34,$85,$32,$85
	.db $ff,$20
	.dw .ref28
	.db $fd
	.dw .song0ch4loop


.song1ch0:
	.db $fb,$03
.song1ch0loop:
.ref30:
	.db $86,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$88,$22,$85,$22,$85,$22,$85
	.db $22,$85
.ref31:
	.db $86,$28,$85,$28,$85,$28,$85,$28,$85,$24,$85,$24,$85,$24,$85,$24
	.db $85
.ref32:
	.db $1a,$85,$1a,$85,$1a,$85,$1a,$85,$88,$22,$85,$22,$85,$22,$85,$22
	.db $85
	.db $ff,$10
	.dw .ref31
	.db $fd
	.dw .song1ch0loop

.song1ch1:
.song1ch1loop:
.ref34:
	.db $84,$40,$85,$41,$44,$a5,$4a,$89
.ref35:
	.db $81,$44,$8d,$40,$8b,$36,$8d,$3a,$85,$36,$85
.ref36:
	.db $8f,$32,$ad
.ref37:
	.db $9f,$00,$9d
	.db $fd
	.dw .song1ch1loop

.song1ch2:
.song1ch2loop:
.ref38:
	.db $82,$1a,$85,$33,$01,$1a,$85,$33,$01,$22,$85,$3b,$01,$22,$85,$3b
	.db $00,$81
.ref39:
	.db $28,$85,$41,$01,$28,$85,$41,$01,$24,$85,$3d,$01,$24,$85,$3d,$00
	.db $81
.ref40:
	.db $1a,$85,$33,$01,$1a,$85,$33,$01,$22,$85,$3b,$01,$22,$85,$3b,$00
	.db $81
	.db $ff,$11
	.dw .ref39
	.db $fd
	.dw .song1ch2loop

.song1ch3:
.song1ch3loop:
.ref42:
	.db $bf
.ref43:
	.db $bf
.ref44:
	.db $bf
.ref45:
	.db $bf
	.db $fd
	.dw .song1ch3loop

.song1ch4:
.song1ch4loop:
.ref46:
	.db $32,$85,$32,$85,$34,$85,$32,$8d,$32,$85,$34,$85,$32,$85
.ref47:
	.db $32,$85,$33,$33,$34,$85,$32,$8d,$32,$85,$34,$85,$32,$85
	.db $ff,$0e
	.dw .ref46
	.db $ff,$0e
	.dw .ref47
	.db $fd
	.dw .song1ch4loop
